Upgrade Ignition Edifice packages
ros-infrastructure/reprepro-updater pull request #131
Opened 2021-11-16 01:42 UTC by chapulina

Similar to #129, periodic update to the latest versions.

I'd like to get this in before #128 , to reduce that PR

One thing I did differently here was to remove the revision `-1` from the versions, because some packages were released as `-2`

2021-11-16 21:49 UTC, nuclearsandwich commented
> One thing I did differently here was to remove the revision `-1` from the versions, because some packages were released as `-2`

In general I'm very much a fan of fully specified releases since there's really no better expression of what we _want_ in the bootstrap repository than these configs. But since we don't have any enforcement that every clause in a filter expression actually matches a package I can't really justify being dogmatic about it. I think it does make sense to include the `-` separator literal to prevent a version such as `1.4.1*` from matching `1.4.11` in addition to the intended `1.4.1-2`.

2021-11-16 21:52 UTC, nuclearsandwich requested changes
Even if we don't include the debinc value in the fixed portion of the version glob I think it's best to include the debinc separator character `-` to prevent unintended matches.

2021-11-16 22:00 UTC, chapulina commented
Makes sense, added the `-` back in 35e4b31

2021-11-16 23:28 UTC, nuclearsandwich approved these changes
There was one "missed" edit common to both files but other than those it looks good and passes CI.

2021-11-16 23:28 UTC, nuclearsandwich commented on config/ignition_edifice_debian_buster.yaml
> +(Package (% =ignition-edifice), $Version (% 1.0.2*)) |\
Looks like one was missed.

```suggestion
(Package (% =ignition-edifice), $Version (% 1.0.2-*)) |\
```

2021-11-16 23:28 UTC, nuclearsandwich commented on config/ignition_edifice_ubuntu_focal.yaml
> +(Package (% =ignition-edifice), $Version (% 1.0.2*)) |\
```suggestion
(Package (% =ignition-edifice), $Version (% 1.0.2-*)) |\
```

2021-11-17 14:40 UTC, merged

2021-11-17 14:56 UTC, nuclearsandwich commented
Import jobs:
https://build.ros.org/job/import_upstream/191/
https://build.ros2.org/job/import_upstream/346/